# Generated by Django 4.2.5 on 2023-11-17 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
